### ISSUE TITLE
"sneak" case should be "snake"

### ISSUE THREAD

**Issue by koterpillar** [aiya000/hs-character-cases#1]
See https://en.wikipedia.org/wiki/Snake_case.

**Comment by aiya000** [comment]
Oops!
The implementation is already fixed, but I forgot to fix README.md.
Thanks!

**Comment by aiya000** [comment]
fixed!
https://github.com/aiya000/hs-character-cases/commit/def65bdc6030837f8f3bb64f4541fea846cad5c6
